# Generated by Django 4.2.7 on 2023-11-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="my blog post", max_length=255),
        ),
    ]
